### ISSUE TITLE
pep8 conflicts with log_configuration.py

### ISSUE THREAD

**Issue by satyammittal** [canihavesomecoffee/sample-platform#58]
Some conflicts with log_configuration file

1. log_configuration.py:5:1: E302 expected 2 blank lines, found 1
2. log_configuration.py:19:8: E101 indentation contains mixed spaces and tabs
3. log_configuration.py:19:8: W191 indentation contains tabs
4. log_configuration.py:19:65: W291 trailing whitespace
5. log_configuration.py:20:1: E101 indentation contains mixed spaces and tabs
6. log_configuration.py:20:1: W191 indentation contains tabs
7. log_configuration.py:21:1: E101 indentation contains mixed spaces and tabs

I would want to send 1 PR.
Thanks

**Comment by grassknoted** [comment]
Could you please be a little more specific, about the conflicts?

**Comment by satyammittal** [comment]
Edited :)

**Comment by canihavesomecoffee** [comment]
Fixed by satyam's PR. Closing issue.

@grassknoted: It's just not good if we start mixing spaces & tabs. All over the project I'm using spaces, and due to me not noticing other contributors using tabs, it's messed up on some places. That mix caused the platform to crash a while ago, so I enabled some checking now for PEP-8 compliancy.
